set( KNIPPTASCH_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX} )

if( HAVE_KDE )
      set( KNIPPTASCH_BIN_INSTALL_DIR ${BIN_INSTALL_DIR}         )
      set( KNIPPTASCH_LIB_INSTALL_DIR ${LIB_INSTALL_DIR}         )
      set( KNIPPTASCH_DATA_INSTALL_DIR ${DATA_INSTALL_DIR}       )
      set( KNIPPTASCH_INCLUDE_INSTALL_DIR ${INCLUDE_INSTALL_DIR} )
      set( KNIPPTASCH_LOCALE_INSTALL_DIR ${LOCALE_INSTALL_DIR}   )
      set( KNIPPTASCH_PLUGIN_INSTALL_DIR ${PLUGIN_INSTALL_DIR}   )
else( HAVE_KDE )
    if( WIN32 )
      set( KNIPPTASCH_BIN_INSTALL_DIR     "${KNIPPTASCH_INSTALL_PREFIX}"                  )
      set( KNIPPTASCH_LIB_INSTALL_DIR     "${KNIPPTASCH_INSTALL_PREFIX}"                  )
      set( KNIPPTASCH_DATA_INSTALL_DIR    "${KNIPPTASCH_INSTALL_PREFIX}/data"             )
      set( KNIPPTASCH_INCLUDE_INSTALL_DIR "${KNIPPTASCH_INSTALL_PREFIX}/include"          )
      set( KNIPPTASCH_LOCALE_INSTALL_DIR  "${KNIPPTASCH_INSTALL_PREFIX}/locale"           )
      set( KNIPPTASCH_PLUGIN_INSTALL_DIR  "${KNIPPTASCH_INSTALL_PREFIX}/plugins"          )
    else( WIN32 )
      set( KNIPPTASCH_BIN_INSTALL_DIR     "${KNIPPTASCH_INSTALL_PREFIX}/bin"              )
      set( KNIPPTASCH_LIB_INSTALL_DIR     "${KNIPPTASCH_INSTALL_PREFIX}/lib"              )
      set( KNIPPTASCH_DATA_INSTALL_DIR    "${KNIPPTASCH_INSTALL_PREFIX}/share/knipptasch" )
      set( KNIPPTASCH_INCLUDE_INSTALL_DIR "${KNIPPTASCH_INSTALL_PREFIX}/include"          )
      set( KNIPPTASCH_LOCALE_INSTALL_DIR  "${KNIPPTASCH_INSTALL_PREFIX}/share/locale"     )
      set( KNIPPTASCH_PLUGIN_INSTALL_DIR  "${KNIPPTASCH_DATA_INSTALL_DIR}/plugins"        )
    endif( WIN32 )

    set( INSTALL_TARGETS_DEFAULT_ARGS
           RUNTIME DESTINATION "${KNIPPTASCH_BIN_INSTALL_DIR}"
           LIBRARY DESTINATION "${KNIPPTASCH_LIB_INSTALL_DIR}"
           ARCHIVE DESTINATION "${KNIPPTASCH_LIB_INSTALL_DIR}" COMPONENT Devel
      )
endif( HAVE_KDE )

message( STATUS "bin install dir:"     ${KNIPPTASCH_BIN_INSTALL_DIR}     )
message( STATUS "lib install dir:"     ${KNIPPTASCH_LIB_INSTALL_DIR}     )
message( STATUS "data install dir:"    ${KNIPPTASCH_DATA_INSTALL_DIR}    )
message( STATUS "include install dir:" ${KNIPPTASCH_INCLUDE_INSTALL_DIR} )
message( STATUS "locale install dir:"  ${KNIPPTASCH_LOCALE_INSTALL_DIR}  )
message( STATUS "plugin install dir:" ${KNIPPTASCH_PLUGIN_INSTALL_DIR}   )
